server:
  port: 9091

spring:
  datasource:
    url: jdbc:h2:file:~/data/orderDB
    driver-class-name: org.h2.Driver
    username: sa
    password: password

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  h2:
    console:
      enabled: true


